apiVersion: v1
kind: Service
metadata:
  name: polls
  labels:
    application: polls
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    application: polls
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: polls
  labels:
    application: polls
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: polls
    spec:
      containers:
      - name: polls-app
        image: mramshaw4docs/python-django-gunicorn:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
