apiVersion: v1
kind: Service
metadata:
  name: polls
  labels:
    application: polls
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    application: polls
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: polls
  labels:
    application: polls
spec:
  replicas: 3
  template:
    metadata:
      labels:
        application: polls
    spec:
      containers:
      - name: polls-app
        image: mramshaw4docs/python-django-gunicorn:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
