apiVersion: v1
kind: Service
metadata:
  name: polls
  labels:
    run: polls
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: polls
